don't call exit in functions

diff --git a/.zshfunctions/repo b/.zshfunctions/repo
--- a/.zshfunctions/repo
+++ b/.zshfunctions/repo
@@ -20,12 +20,12 @@ base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
 # Validate that this folder is a git folder
 if ! git branch 2>/dev/null 1>&2 ; then
 	echo "Not a git repo!"
-	exit $?
+	return $?
 fi
 
 # Find current directory relative to .git parent
 	full_path=$(pwd)
-git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
+git_base_path=$(cd "./$(git rev-parse --show-cdup)" || return 1; pwd)
 relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
 
 # If filename argument is present, append it
@@ -45,5 +45,5 @@ url="$base_url/$tree/$branch$relative_path"
 
 echo "Calling $(type open) for $url"
 
-open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
+open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && return 1);
 
